set_property mark_debug true [get_nets [list {i2s_in_tdata[13]} {i2s_in_tdata[1]} {i2s_in_tdata[0]} {i2s_in_tdata[2]} {i2s_in_tdata[3]} {i2s_in_tdata[4]} {i2s_in_tdata[5]} {i2s_in_tdata[6]} {i2s_in_tdata[7]} {i2s_in_tdata[14]} {i2s_in_tdata[15]} {i2s_in_tdata[12]} {i2s_in_tdata[8]} {i2s_in_tdata[9]} {i2s_in_tdata[10]} {i2s_in_tdata[11]} {i2s_in_tdata[16]} {i2s_in_tdata[22]} {i2s_in_tdata[23]} {i2s_in_tdata[20]} {i2s_in_tdata[21]} {i2s_in_tdata[17]} {i2s_in_tdata[18]} {i2s_in_tdata[19]} {i2s_in_tdata[24]} {i2s_in_tdata[30]} {i2s_in_tdata[31]} {i2s_in_tdata[28]} {i2s_in_tdata[29]} {i2s_in_tdata[25]} {i2s_in_tdata[26]} {i2s_in_tdata[27]}]]
set_property mark_debug true [get_nets [list i2s_in_tlast]]
set_property mark_debug true [get_nets [list i2s_in_tready]]
set_property mark_debug true [get_nets [list i2s_out_tready]]
set_property mark_debug true [get_nets [list i2s_out_tvalid]]
set_property mark_debug true [get_nets [list {i2s_out_tdata[13]} {i2s_out_tdata[1]} {i2s_out_tdata[0]} {i2s_out_tdata[2]} {i2s_out_tdata[3]} {i2s_out_tdata[4]} {i2s_out_tdata[14]} {i2s_out_tdata[15]} {i2s_out_tdata[16]} {i2s_out_tdata[5]} {i2s_out_tdata[6]} {i2s_out_tdata[7]} {i2s_out_tdata[8]} {i2s_out_tdata[9]} {i2s_out_tdata[10]} {i2s_out_tdata[11]} {i2s_out_tdata[12]} {i2s_out_tdata[21]} {i2s_out_tdata[22]} {i2s_out_tdata[23]} {i2s_out_tdata[24]} {i2s_out_tdata[17]} {i2s_out_tdata[18]} {i2s_out_tdata[19]} {i2s_out_tdata[20]} {i2s_out_tdata[29]} {i2s_out_tdata[30]} {i2s_out_tdata[31]} {i2s_out_tdata[25]} {i2s_out_tdata[26]} {i2s_out_tdata[27]} {i2s_out_tdata[28]}]]
set_property mark_debug true [get_nets [list i2s_out_data_OBUF]]
set_property mark_debug true [get_nets [list i2s_in_data_IBUF]]
set_property mark_debug true [get_nets [list {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[4]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[0]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[1]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[2]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[3]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[5]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[6]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[7]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[8]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[11]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[13]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[15]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[16]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[14]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[12]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[9]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[25]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[27]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[29]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[31]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[30]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[28]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[26]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[17]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[19]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[21]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[23]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[24]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[22]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[20]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[18]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[10]}]]
set_property mark_debug true [get_nets [list {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[9]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[5]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[6]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[19]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[20]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[17]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[18]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[15]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[16]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[7]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[8]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[10]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[11]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[21]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[23]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[25]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[27]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[28]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[26]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[24]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[22]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[31]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[29]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[30]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[12]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[13]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[14]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[0]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[1]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[2]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[3]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[4]}]]
set_property mark_debug true [get_nets [list bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tready]]
set_property mark_debug true [get_nets [list bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tvalid]]
set_property mark_debug true [get_nets [list bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tlast]]
set_property mark_debug true [get_nets [list bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tlast]]
set_property mark_debug true [get_nets [list bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tready]]
set_property mark_debug true [get_nets [list bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tvalid]]
create_debug_core u_ila_0 ila
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
connect_debug_port u_ila_0/clk [get_nets [list bd_inst/design_1_i/processing_system7_0/inst/FCLK_CLK0 ]]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[0]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[1]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[2]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[3]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[4]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[5]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[6]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[7]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[8]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[9]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[10]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[11]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[12]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[13]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[14]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[15]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[16]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[17]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[18]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[19]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[20]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[21]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[22]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[23]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[24]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[25]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[26]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[27]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[28]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[29]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[30]} {bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tdata[31]} ]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[0]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[1]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[2]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[3]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[4]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[5]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[6]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[7]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[8]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[9]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[10]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[11]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[12]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[13]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[14]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[15]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[16]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[17]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[18]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[19]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[20]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[21]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[22]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[23]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[24]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[25]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[26]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[27]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[28]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[29]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[30]} {bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tdata[31]} ]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {i2s_out_tdata[0]} {i2s_out_tdata[1]} {i2s_out_tdata[2]} {i2s_out_tdata[3]} {i2s_out_tdata[4]} {i2s_out_tdata[5]} {i2s_out_tdata[6]} {i2s_out_tdata[7]} {i2s_out_tdata[8]} {i2s_out_tdata[9]} {i2s_out_tdata[10]} {i2s_out_tdata[11]} {i2s_out_tdata[12]} {i2s_out_tdata[13]} {i2s_out_tdata[14]} {i2s_out_tdata[15]} {i2s_out_tdata[16]} {i2s_out_tdata[17]} {i2s_out_tdata[18]} {i2s_out_tdata[19]} {i2s_out_tdata[20]} {i2s_out_tdata[21]} {i2s_out_tdata[22]} {i2s_out_tdata[23]} {i2s_out_tdata[24]} {i2s_out_tdata[25]} {i2s_out_tdata[26]} {i2s_out_tdata[27]} {i2s_out_tdata[28]} {i2s_out_tdata[29]} {i2s_out_tdata[30]} {i2s_out_tdata[31]} ]]
create_debug_port u_ila_0 probe
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {i2s_in_tdata[0]} {i2s_in_tdata[1]} {i2s_in_tdata[2]} {i2s_in_tdata[3]} {i2s_in_tdata[4]} {i2s_in_tdata[5]} {i2s_in_tdata[6]} {i2s_in_tdata[7]} {i2s_in_tdata[8]} {i2s_in_tdata[9]} {i2s_in_tdata[10]} {i2s_in_tdata[11]} {i2s_in_tdata[12]} {i2s_in_tdata[13]} {i2s_in_tdata[14]} {i2s_in_tdata[15]} {i2s_in_tdata[16]} {i2s_in_tdata[17]} {i2s_in_tdata[18]} {i2s_in_tdata[19]} {i2s_in_tdata[20]} {i2s_in_tdata[21]} {i2s_in_tdata[22]} {i2s_in_tdata[23]} {i2s_in_tdata[24]} {i2s_in_tdata[25]} {i2s_in_tdata[26]} {i2s_in_tdata[27]} {i2s_in_tdata[28]} {i2s_in_tdata[29]} {i2s_in_tdata[30]} {i2s_in_tdata[31]} ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list i2s_in_data_IBUF ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list i2s_in_tlast ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list i2s_in_tready ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list i2s_out_data_OBUF ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list i2s_out_tready ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list i2s_out_tvalid ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tlast ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tready ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list bd_inst/design_1_i/axi_dma_0/m_axis_mm2s_tvalid ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tlast ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tready ]]
create_debug_port u_ila_0 probe
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list bd_inst/design_1_i/axi_dma_0/s_axis_s2mm_tvalid ]]

